// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invoice.sql

package db

import (
	"context"
)

const countInvoicesByStatus = `-- name: CountInvoicesByStatus :one
SELECT COUNT(*)
FROM invoices
WHERE status = $1
`

func (q *Queries) CountInvoicesByStatus(ctx context.Context, status string) (int64, error) {
	row := q.db.QueryRow(ctx, countInvoicesByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createInvoice = `-- name: CreateInvoice :one
INSERT INTO invoices (
    work_order_id,
    customer_id,
    total_amount,
    status
)
VALUES ($1, $2, $3, $4)
RETURNING id, work_order_id, customer_id, total_amount, status, created_at
`

type CreateInvoiceParams struct {
	WorkOrderID int32
	CustomerID  int32
	TotalAmount float64
	Status      string
}

func (q *Queries) CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, createInvoice,
		arg.WorkOrderID,
		arg.CustomerID,
		arg.TotalAmount,
		arg.Status,
	)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.WorkOrderID,
		&i.CustomerID,
		&i.TotalAmount,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const deleteInvoice = `-- name: DeleteInvoice :exec
DELETE FROM invoices
WHERE id = $1
`

func (q *Queries) DeleteInvoice(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteInvoice, id)
	return err
}

const getInvoice = `-- name: GetInvoice :one
SELECT id, work_order_id, customer_id, total_amount, status, created_at
FROM invoices
WHERE id = $1
`

func (q *Queries) GetInvoice(ctx context.Context, id int32) (Invoice, error) {
	row := q.db.QueryRow(ctx, getInvoice, id)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.WorkOrderID,
		&i.CustomerID,
		&i.TotalAmount,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getInvoicesByStatus = `-- name: GetInvoicesByStatus :many
SELECT id, work_order_id, customer_id, total_amount, status, created_at
FROM invoices
WHERE status = $1
ORDER BY id
`

func (q *Queries) GetInvoicesByStatus(ctx context.Context, status string) ([]Invoice, error) {
	rows, err := q.db.Query(ctx, getInvoicesByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Invoice
	for rows.Next() {
		var i Invoice
		if err := rows.Scan(
			&i.ID,
			&i.WorkOrderID,
			&i.CustomerID,
			&i.TotalAmount,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkOrderForInvoice = `-- name: GetWorkOrderForInvoice :one
SELECT id, quotation_id, customer_id, vehicle_id, status, due_date, created_at
FROM work_orders
WHERE id = $1
`

func (q *Queries) GetWorkOrderForInvoice(ctx context.Context, id int32) (WorkOrder, error) {
	row := q.db.QueryRow(ctx, getWorkOrderForInvoice, id)
	var i WorkOrder
	err := row.Scan(
		&i.ID,
		&i.QuotationID,
		&i.CustomerID,
		&i.VehicleID,
		&i.Status,
		&i.DueDate,
		&i.CreatedAt,
	)
	return i, err
}

const listInvoices = `-- name: ListInvoices :many
SELECT id, work_order_id, customer_id, total_amount, status, created_at
FROM invoices
ORDER BY id
`

func (q *Queries) ListInvoices(ctx context.Context) ([]Invoice, error) {
	rows, err := q.db.Query(ctx, listInvoices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Invoice
	for rows.Next() {
		var i Invoice
		if err := rows.Scan(
			&i.ID,
			&i.WorkOrderID,
			&i.CustomerID,
			&i.TotalAmount,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInvoiceStatus = `-- name: UpdateInvoiceStatus :one
UPDATE invoices
SET status = $1
WHERE id = $2
RETURNING id, work_order_id, customer_id, total_amount, status, created_at
`

type UpdateInvoiceStatusParams struct {
	Status string
	ID     int32
}

func (q *Queries) UpdateInvoiceStatus(ctx context.Context, arg UpdateInvoiceStatusParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, updateInvoiceStatus, arg.Status, arg.ID)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.WorkOrderID,
		&i.CustomerID,
		&i.TotalAmount,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
