// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Customer struct {
	ID        int32
	Name      string
	Phone     string
	Email     pgtype.Text
	CreatedAt pgtype.Timestamp
}

type Invoice struct {
	ID          int32
	WorkOrderID int32
	CustomerID  int32
	TotalAmount float64
	Status      string
	CreatedAt   pgtype.Timestamp
}

type Payment struct {
	ID            int32
	InvoiceID     int32
	Amount        float64
	PaymentMethod string
	PaymentDate   pgtype.Timestamp
}

type Quotation struct {
	ID          int32
	CustomerID  int32
	VehicleID   int32
	Status      string
	TotalAmount float64
	CreatedAt   pgtype.Timestamp
}

type QuotationItem struct {
	ID          int32
	QuotationID int32
	ServiceID   int32
	Quantity    int32
	Price       float64
	Amount      float64
}

type Service struct {
	ID          int32
	Name        string
	Description pgtype.Text
	Price       float64
	CreatedAt   pgtype.Timestamp
}

type Vehicle struct {
	ID          int32
	CustomerID  int32
	RegNo       string
	VehicleType string
	CreatedAt   pgtype.Timestamp
}

type WorkOrder struct {
	ID          int32
	QuotationID int32
	CustomerID  int32
	VehicleID   int32
	Status      string
	DueDate     pgtype.Date
	CreatedAt   pgtype.Timestamp
}
