// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payment.sql

package db

import (
	"context"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (
    invoice_id,
    amount,
    payment_method
)
VALUES ($1, $2, $3)
RETURNING id, invoice_id, amount, payment_method, payment_date
`

type CreatePaymentParams struct {
	InvoiceID     int32
	Amount        float64
	PaymentMethod string
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment, arg.InvoiceID, arg.Amount, arg.PaymentMethod)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.Amount,
		&i.PaymentMethod,
		&i.PaymentDate,
	)
	return i, err
}

const deletePayment = `-- name: DeletePayment :exec
DELETE FROM payments
WHERE id = $1
`

func (q *Queries) DeletePayment(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deletePayment, id)
	return err
}

const getPayment = `-- name: GetPayment :one
SELECT id, invoice_id, amount, payment_method, payment_date
FROM payments
WHERE id = $1
`

func (q *Queries) GetPayment(ctx context.Context, id int32) (Payment, error) {
	row := q.db.QueryRow(ctx, getPayment, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.Amount,
		&i.PaymentMethod,
		&i.PaymentDate,
	)
	return i, err
}

const getPaymentsByInvoice = `-- name: GetPaymentsByInvoice :many
SELECT id, invoice_id, amount, payment_method, payment_date
FROM payments
WHERE invoice_id = $1
ORDER BY id
`

func (q *Queries) GetPaymentsByInvoice(ctx context.Context, invoiceID int32) ([]Payment, error) {
	rows, err := q.db.Query(ctx, getPaymentsByInvoice, invoiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceID,
			&i.Amount,
			&i.PaymentMethod,
			&i.PaymentDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTotalRevenue = `-- name: GetTotalRevenue :one
SELECT COALESCE(SUM(amount), 0)
FROM payments
`

func (q *Queries) GetTotalRevenue(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRow(ctx, getTotalRevenue)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const listPayments = `-- name: ListPayments :many
SELECT id, invoice_id, amount, payment_method, payment_date
FROM payments
ORDER BY id
`

func (q *Queries) ListPayments(ctx context.Context) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPayments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceID,
			&i.Amount,
			&i.PaymentMethod,
			&i.PaymentDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
