// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: quotation.sql

package db

import (
	"context"
)

const addQuotationItem = `-- name: AddQuotationItem :one
INSERT INTO quotation_items (
    quotation_id,
    service_id,
    quantity,
    price,
    amount
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, quotation_id, service_id, quantity, price, amount
`

type AddQuotationItemParams struct {
	QuotationID int32
	ServiceID   int32
	Quantity    int32
	Price       float64
	Amount      float64
}

func (q *Queries) AddQuotationItem(ctx context.Context, arg AddQuotationItemParams) (QuotationItem, error) {
	row := q.db.QueryRow(ctx, addQuotationItem,
		arg.QuotationID,
		arg.ServiceID,
		arg.Quantity,
		arg.Price,
		arg.Amount,
	)
	var i QuotationItem
	err := row.Scan(
		&i.ID,
		&i.QuotationID,
		&i.ServiceID,
		&i.Quantity,
		&i.Price,
		&i.Amount,
	)
	return i, err
}

const createQuotation = `-- name: CreateQuotation :one
INSERT INTO quotations (
    customer_id,
    vehicle_id,
    status,
    total_amount
)
VALUES ($1, $2, $3, $4)
RETURNING id, customer_id, vehicle_id, status, total_amount, created_at
`

type CreateQuotationParams struct {
	CustomerID  int32
	VehicleID   int32
	Status      string
	TotalAmount float64
}

func (q *Queries) CreateQuotation(ctx context.Context, arg CreateQuotationParams) (Quotation, error) {
	row := q.db.QueryRow(ctx, createQuotation,
		arg.CustomerID,
		arg.VehicleID,
		arg.Status,
		arg.TotalAmount,
	)
	var i Quotation
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.VehicleID,
		&i.Status,
		&i.TotalAmount,
		&i.CreatedAt,
	)
	return i, err
}

const deleteQuotation = `-- name: DeleteQuotation :exec
DELETE FROM quotations
WHERE id = $1
`

func (q *Queries) DeleteQuotation(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteQuotation, id)
	return err
}

const getQuotation = `-- name: GetQuotation :one
SELECT id, customer_id, vehicle_id, status, total_amount, created_at
FROM quotations
WHERE id = $1
`

func (q *Queries) GetQuotation(ctx context.Context, id int32) (Quotation, error) {
	row := q.db.QueryRow(ctx, getQuotation, id)
	var i Quotation
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.VehicleID,
		&i.Status,
		&i.TotalAmount,
		&i.CreatedAt,
	)
	return i, err
}

const getQuotationItems = `-- name: GetQuotationItems :many
SELECT
    id,
    quotation_id,
    service_id,
    quantity,
    price,
    amount
FROM quotation_items
WHERE quotation_id = $1
ORDER BY id
`

func (q *Queries) GetQuotationItems(ctx context.Context, quotationID int32) ([]QuotationItem, error) {
	rows, err := q.db.Query(ctx, getQuotationItems, quotationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QuotationItem
	for rows.Next() {
		var i QuotationItem
		if err := rows.Scan(
			&i.ID,
			&i.QuotationID,
			&i.ServiceID,
			&i.Quantity,
			&i.Price,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getQuotationsByStatus = `-- name: GetQuotationsByStatus :many
SELECT id, customer_id, vehicle_id, status, total_amount, created_at
FROM quotations
WHERE status = $1
ORDER BY id
`

func (q *Queries) GetQuotationsByStatus(ctx context.Context, status string) ([]Quotation, error) {
	rows, err := q.db.Query(ctx, getQuotationsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Quotation
	for rows.Next() {
		var i Quotation
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.VehicleID,
			&i.Status,
			&i.TotalAmount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuotations = `-- name: ListQuotations :many
SELECT id, customer_id, vehicle_id, status, total_amount, created_at
FROM quotations
ORDER BY id
`

func (q *Queries) ListQuotations(ctx context.Context) ([]Quotation, error) {
	rows, err := q.db.Query(ctx, listQuotations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Quotation
	for rows.Next() {
		var i Quotation
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.VehicleID,
			&i.Status,
			&i.TotalAmount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateQuotationStatus = `-- name: UpdateQuotationStatus :one
UPDATE quotations
SET status = $1
WHERE id = $2
RETURNING id, customer_id, vehicle_id, status, total_amount, created_at
`

type UpdateQuotationStatusParams struct {
	Status string
	ID     int32
}

func (q *Queries) UpdateQuotationStatus(ctx context.Context, arg UpdateQuotationStatusParams) (Quotation, error) {
	row := q.db.QueryRow(ctx, updateQuotationStatus, arg.Status, arg.ID)
	var i Quotation
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.VehicleID,
		&i.Status,
		&i.TotalAmount,
		&i.CreatedAt,
	)
	return i, err
}
