// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vehicle.sql

package db

import (
	"context"
)

const createVehicle = `-- name: CreateVehicle :one
INSERT INTO vehicles(customer_id,reg_no,vehicle_type) VALUES ($1,$2,$3)
RETURNING id,customer_id,reg_no,vehicle_type,created_at
`

type CreateVehicleParams struct {
	CustomerID  int32
	RegNo       string
	VehicleType string
}

func (q *Queries) CreateVehicle(ctx context.Context, arg CreateVehicleParams) (Vehicle, error) {
	row := q.db.QueryRow(ctx, createVehicle, arg.CustomerID, arg.RegNo, arg.VehicleType)
	var i Vehicle
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.RegNo,
		&i.VehicleType,
		&i.CreatedAt,
	)
	return i, err
}

const deleteVehicle = `-- name: DeleteVehicle :exec
DELETE FROM vehicles
WHERE id = $1
`

func (q *Queries) DeleteVehicle(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteVehicle, id)
	return err
}

const getVehicle = `-- name: GetVehicle :one
SELECT id, customer_id, reg_no, vehicle_type, created_at
FROM vehicles
WHERE id = $1
`

func (q *Queries) GetVehicle(ctx context.Context, id int32) (Vehicle, error) {
	row := q.db.QueryRow(ctx, getVehicle, id)
	var i Vehicle
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.RegNo,
		&i.VehicleType,
		&i.CreatedAt,
	)
	return i, err
}

const getVehiclesByCustomerID = `-- name: GetVehiclesByCustomerID :many
SELECT id, customer_id, reg_no, vehicle_type, created_at
FROM vehicles
WHERE customer_id = $1
ORDER BY id
`

func (q *Queries) GetVehiclesByCustomerID(ctx context.Context, customerID int32) ([]Vehicle, error) {
	rows, err := q.db.Query(ctx, getVehiclesByCustomerID, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Vehicle
	for rows.Next() {
		var i Vehicle
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.RegNo,
			&i.VehicleType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVehicles = `-- name: ListVehicles :many
SELECT id, customer_id, reg_no, vehicle_type, created_at
FROM vehicles
ORDER BY id
`

func (q *Queries) ListVehicles(ctx context.Context) ([]Vehicle, error) {
	rows, err := q.db.Query(ctx, listVehicles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Vehicle
	for rows.Next() {
		var i Vehicle
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.RegNo,
			&i.VehicleType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVehicle = `-- name: UpdateVehicle :one
UPDATE vehicles
SET
    customer_id = $1,
    reg_no = $2,
    vehicle_type = $3
WHERE id = $4
RETURNING id, customer_id, reg_no, vehicle_type, created_at
`

type UpdateVehicleParams struct {
	CustomerID  int32
	RegNo       string
	VehicleType string
	ID          int32
}

func (q *Queries) UpdateVehicle(ctx context.Context, arg UpdateVehicleParams) (Vehicle, error) {
	row := q.db.QueryRow(ctx, updateVehicle,
		arg.CustomerID,
		arg.RegNo,
		arg.VehicleType,
		arg.ID,
	)
	var i Vehicle
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.RegNo,
		&i.VehicleType,
		&i.CreatedAt,
	)
	return i, err
}
