// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vehicle.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVehicle = `-- name: CreateVehicle :one
INSERT INTO vehicles(customer_id,reg_no,vehicle_type) VALUES ($1,$2,$3)
RETURNING id,customer_id,reg_no,vehicle_type,created_at
`

type CreateVehicleParams struct {
	CustomerID  int32
	RegNo       string
	VehicleType string
}

type CreateVehicleRow struct {
	ID          int32
	CustomerID  int32
	RegNo       string
	VehicleType string
	CreatedAt   pgtype.Timestamp
}

func (q *Queries) CreateVehicle(ctx context.Context, arg CreateVehicleParams) (CreateVehicleRow, error) {
	row := q.db.QueryRow(ctx, createVehicle, arg.CustomerID, arg.RegNo, arg.VehicleType)
	var i CreateVehicleRow
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.RegNo,
		&i.VehicleType,
		&i.CreatedAt,
	)
	return i, err
}

const deleteVehicle = `-- name: DeleteVehicle :exec
UPDATE vehicles
SET deleted_at = CURRENT_TIMESTAMP
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) DeleteVehicle(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteVehicle, id)
	return err
}

const getVehicle = `-- name: GetVehicle :one
SELECT
    v.id,
    v.customer_id,
    v.reg_no,
    v.vehicle_type,
    v.created_at
FROM vehicles v
JOIN customers c ON c.id = v.customer_id
WHERE v.id = $1
  AND v.deleted_at IS NULL
  AND c.deleted_at IS NULL
`

type GetVehicleRow struct {
	ID          int32
	CustomerID  int32
	RegNo       string
	VehicleType string
	CreatedAt   pgtype.Timestamp
}

func (q *Queries) GetVehicle(ctx context.Context, id int32) (GetVehicleRow, error) {
	row := q.db.QueryRow(ctx, getVehicle, id)
	var i GetVehicleRow
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.RegNo,
		&i.VehicleType,
		&i.CreatedAt,
	)
	return i, err
}

const getVehiclesByCustomerID = `-- name: GetVehiclesByCustomerID :many
SELECT
    v.id,
    v.customer_id,
    v.reg_no,
    v.vehicle_type,
    v.created_at
FROM vehicles v
JOIN customers c ON c.id = v.customer_id
WHERE v.customer_id = $1
  AND v.deleted_at IS NULL
  AND c.deleted_at IS NULL
ORDER BY v.id
`

type GetVehiclesByCustomerIDRow struct {
	ID          int32
	CustomerID  int32
	RegNo       string
	VehicleType string
	CreatedAt   pgtype.Timestamp
}

func (q *Queries) GetVehiclesByCustomerID(ctx context.Context, customerID int32) ([]GetVehiclesByCustomerIDRow, error) {
	rows, err := q.db.Query(ctx, getVehiclesByCustomerID, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetVehiclesByCustomerIDRow
	for rows.Next() {
		var i GetVehiclesByCustomerIDRow
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.RegNo,
			&i.VehicleType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVehicles = `-- name: ListVehicles :many
SELECT
    v.id,
    v.customer_id,
    v.reg_no,
    v.vehicle_type,
    v.created_at,
    c.name AS customer_name
FROM vehicles v
JOIN customers c ON c.id = v.customer_id
WHERE v.deleted_at IS NULL
  AND c.deleted_at IS NULL
ORDER BY v.id
`

type ListVehiclesRow struct {
	ID           int32
	CustomerID   int32
	RegNo        string
	VehicleType  string
	CreatedAt    pgtype.Timestamp
	CustomerName string
}

func (q *Queries) ListVehicles(ctx context.Context) ([]ListVehiclesRow, error) {
	rows, err := q.db.Query(ctx, listVehicles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVehiclesRow
	for rows.Next() {
		var i ListVehiclesRow
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.RegNo,
			&i.VehicleType,
			&i.CreatedAt,
			&i.CustomerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVehicle = `-- name: UpdateVehicle :one
UPDATE vehicles
SET
    customer_id = $1,
    reg_no = $2,
    vehicle_type = $3
WHERE id = $4
  AND deleted_at IS NULL
RETURNING id, customer_id, reg_no, vehicle_type, created_at
`

type UpdateVehicleParams struct {
	CustomerID  int32
	RegNo       string
	VehicleType string
	ID          int32
}

type UpdateVehicleRow struct {
	ID          int32
	CustomerID  int32
	RegNo       string
	VehicleType string
	CreatedAt   pgtype.Timestamp
}

func (q *Queries) UpdateVehicle(ctx context.Context, arg UpdateVehicleParams) (UpdateVehicleRow, error) {
	row := q.db.QueryRow(ctx, updateVehicle,
		arg.CustomerID,
		arg.RegNo,
		arg.VehicleType,
		arg.ID,
	)
	var i UpdateVehicleRow
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.RegNo,
		&i.VehicleType,
		&i.CreatedAt,
	)
	return i, err
}
