// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: work_order.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countWorkOrdersByStatus = `-- name: CountWorkOrdersByStatus :one
SELECT COUNT(*)
FROM work_orders
WHERE status = $1
`

func (q *Queries) CountWorkOrdersByStatus(ctx context.Context, status string) (int64, error) {
	row := q.db.QueryRow(ctx, countWorkOrdersByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWorkOrder = `-- name: CreateWorkOrder :one
INSERT INTO work_orders (
    quotation_id,
    customer_id,
    vehicle_id,
    status,
    due_date
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, quotation_id, customer_id, vehicle_id, status, due_date, created_at
`

type CreateWorkOrderParams struct {
	QuotationID int32
	CustomerID  int32
	VehicleID   int32
	Status      string
	DueDate     pgtype.Date
}

func (q *Queries) CreateWorkOrder(ctx context.Context, arg CreateWorkOrderParams) (WorkOrder, error) {
	row := q.db.QueryRow(ctx, createWorkOrder,
		arg.QuotationID,
		arg.CustomerID,
		arg.VehicleID,
		arg.Status,
		arg.DueDate,
	)
	var i WorkOrder
	err := row.Scan(
		&i.ID,
		&i.QuotationID,
		&i.CustomerID,
		&i.VehicleID,
		&i.Status,
		&i.DueDate,
		&i.CreatedAt,
	)
	return i, err
}

const deleteWorkOrder = `-- name: DeleteWorkOrder :exec
DELETE FROM work_orders
WHERE id = $1
`

func (q *Queries) DeleteWorkOrder(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteWorkOrder, id)
	return err
}

const getWorkOrder = `-- name: GetWorkOrder :one
SELECT
    id,
    quotation_id,
    customer_id,
    vehicle_id,
    status,
    due_date,
    created_at
FROM work_orders
WHERE id = $1
`

func (q *Queries) GetWorkOrder(ctx context.Context, id int32) (WorkOrder, error) {
	row := q.db.QueryRow(ctx, getWorkOrder, id)
	var i WorkOrder
	err := row.Scan(
		&i.ID,
		&i.QuotationID,
		&i.CustomerID,
		&i.VehicleID,
		&i.Status,
		&i.DueDate,
		&i.CreatedAt,
	)
	return i, err
}

const getWorkOrdersByStatus = `-- name: GetWorkOrdersByStatus :many
SELECT id, quotation_id, customer_id, vehicle_id, status, due_date, created_at
FROM work_orders
WHERE status = $1
ORDER BY id
`

func (q *Queries) GetWorkOrdersByStatus(ctx context.Context, status string) ([]WorkOrder, error) {
	rows, err := q.db.Query(ctx, getWorkOrdersByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkOrder
	for rows.Next() {
		var i WorkOrder
		if err := rows.Scan(
			&i.ID,
			&i.QuotationID,
			&i.CustomerID,
			&i.VehicleID,
			&i.Status,
			&i.DueDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkOrders = `-- name: ListWorkOrders :many
SELECT
    id,
    quotation_id,
    customer_id,
    vehicle_id,
    status,
    due_date,
    created_at
FROM work_orders
ORDER BY id
`

func (q *Queries) ListWorkOrders(ctx context.Context) ([]WorkOrder, error) {
	rows, err := q.db.Query(ctx, listWorkOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkOrder
	for rows.Next() {
		var i WorkOrder
		if err := rows.Scan(
			&i.ID,
			&i.QuotationID,
			&i.CustomerID,
			&i.VehicleID,
			&i.Status,
			&i.DueDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorkOrderStatus = `-- name: UpdateWorkOrderStatus :one
UPDATE work_orders
SET status = $1
WHERE id = $2
RETURNING id, quotation_id, customer_id, vehicle_id, status, due_date, created_at
`

type UpdateWorkOrderStatusParams struct {
	Status string
	ID     int32
}

func (q *Queries) UpdateWorkOrderStatus(ctx context.Context, arg UpdateWorkOrderStatusParams) (WorkOrder, error) {
	row := q.db.QueryRow(ctx, updateWorkOrderStatus, arg.Status, arg.ID)
	var i WorkOrder
	err := row.Scan(
		&i.ID,
		&i.QuotationID,
		&i.CustomerID,
		&i.VehicleID,
		&i.Status,
		&i.DueDate,
		&i.CreatedAt,
	)
	return i, err
}
